### ISSUE TITLE
Resolution Cheats are Broken in Sonic Frontiers 1.2.0

### ISSUE THREAD

**Issue by SavXL** [ChanseyIsTheBest/NX-60FPS-RES-GFX-Cheats#18]
Title. I believe it's because they haven't been updated for 1.2.0 and are still using the 1.1.1 BID. Putting the 1.1.1 cheats in the txt file named after the 1.2.0 BID seems to have no effect and thus make the 60 FPS cheat made for 1.2.0 not work correctly either. I'm currently getting 60 in menus, 30-37 in Cyberspace, and 30 in the open zone even with max oc.

**Comment by ChanseyIsTheBest** [comment]
When you copy a cheat from another file unless it from an older version of a game to a newer version of the game it will most likely not work as you have found out. This is because developers' update the main of the game which changes the offsets in memory that cheats use.

New cheats have to made by someone to control the dynamic resolution of this game for the latest version for 60FPS to be achievable in the 3D environments of the game. I have previously tested Frontiers without using resolution cheats and have found similar results on 1.1.1 to corroborate what you have found.
