### ISSUE TITLE
Broken 60FPS cheat for Mario Kart 8 Deluxe (Version 2.4)

### ISSUE THREAD

**Issue by exhalum** [ChanseyIsTheBest/NX-60FPS-RES-GFX-Cheats#31]
Hello,

First off , thank you very much for the hard work that must've gone into all the title cheats.
I just wanted to report that that the MK8 3-4 player 60 FPS cheat no longer works as of a few days ago after the latest update. (Update 2.4)

Located here:
https://github.com/ChanseyIsTheBest/NX-60FPS-RES-GFX-Cheats/blob/main/titles/0100152000022000/cheats/13296B64DFA7A131.txt

Version Details here:
https://nintendoeverything.com/mario-kart-8-deluxe-update-out-now-version-2-4-0-patch-notes/

Thanks again

**Comment by ChanseyIsTheBest** [comment]
I wouldn't describe the cheat as broken per say, because cheats usually only work with one version of a game. I'll post my explanation from a previous issue;

'When you copy a cheat from an older version of a game to a newer version of the game without changing it it will most likely not work as you have found out. This is because developers' update the main of the game usually changes the offsets in memory that cheats use.'

The cheat will eventually be updated when someone gets around to it. It can be updated with [Interactive ASM Cheats Updater](https://github.com/zzpong/Interactive-ASM-Cheats-Updater) because it's a main cheat converted from pchtxt. The program is easy to use if you don't want to wait around.

**Comment by ChanseyIsTheBest** [comment]
B3711 updated the cheat to the latest version, you can find it here.

https://github.com/ChanseyIsTheBest/NX-60FPS-RES-GFX-Cheats/blob/main/titles/0100152000022000/cheats/4B7A0BB5AE57E627.txt

**Comment by exhalum** [comment]
Thank you so much

**Comment by yogithesymbian** [comment]
sory if not related but can you update for one piece pirate 4 warior ? v1.6.0 mods fps onigashima ?

**Comment by ChanseyIsTheBest** [comment]
> sory if not related but can you please update for one piece pirate 4 warior ? v1.6.0 mods fps onigashima ?

Can you try FPSLocker to uncap the framerate or try to uncap the framerate in an emulator using Control+U for yuzu or F1 for Ryujinx first?
